//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserId { get; set; }
        [DisplayName("Korisnicko ime")]
        public string UserName { get; set; }
        [DisplayName("Lozinka")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Role { get; set; }

        public string ErrorMessage { get; set; }
    }
}
